
name: Build DogAuto APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME_17_X64: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install SDK tools and build-tools 30.0.3
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: "30.0.3"
          accept-licenses: true

      - name: Generate test keystore
        run: |
          keytool -genkeypair -v -keystore app/dogauto.jks -storepass dogautopass -keypass dogautopass -alias dogauto -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Dog Auto, OU=Dev, O=Dog, L=City, ST=State, C=IN"

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build APKs
        run: ./gradlew assembleDebug assembleRelease --stacktrace

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DogAuto-APK
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release.apk
